sudo: false
language: node_js
node_js:
- 8.1.2
- node
services:
- mongodb
before_script:
- sleep 5
script:
- mongod --version
- npm run-script coveralls
deploy:
  provider: npm
  email: randoapp.me@gmail.com
  api_key:
    secure: W42fP4K6mll5zTVXOi6wXLHhqUakEIuPZ+cuy1PncB3xtIJlcQKrk9XssGNHc71rPTEXX2rTNl4XlZXCCKzeIS3V0syll0ZLLXiA0geXKVi5IjZka6BSFbl3daqtH89EgUQnu4CzF6aqTVD+X6SCFnz4xDfAvr15j3dJTu3alR4=
  on:
    tags: true
    repo: RandoApp/Rando-db
