language: node_js
node_js:
  - 4
  - 5
  - 6
  - node
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - sleep 10
after_script:
  - npm run-script coveralls
