sudo: false
language: node_js
node_js:
  - 7
  - node
services:
- mongodb
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - sleep 15
script:
  - npm run-script coveralls
