language: node_js
node_js:
  - 4
  - 5
  - 6
  - node
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
after_script:
  - npm run-script coveralls
