sudo: false
language: node_js
node_js:
  - 7
  - 8.1.2
services:
- mongodb
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - sleep 5
script:
  - npm run-script coveralls
