language: node_js
node_js:
  - 4
  - 7
  - node
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.4-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - sleep 10
before_install: 
  - if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi
script:
  - npm test